version: 2
updates:
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directories:
      - /shell
      - /launcher
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
